[package]
name = "catastrophicc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
paw.workspace = true
structopt.workspace = true
catastrophic-error = { path = "../libs/error" }
catastrophic-parser = { path = "../libs/parser" }
catastrophic-analyser = { path = "../libs/analyser" }
catastrophic-interpreter = { path = "../libs/interpreter" }