[package]
name = "catastrophic"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
catastrophic-analyser = { path = "analyser" }
catastrophic-parser = { path = "parser" }
paw = "1.0.0"
structopt = { version = "0.3.22", features = ["paw"] }

[workspace]
