[workspace]
members = [
    "libs/core", 
    "libs/parser", 
    "libs/ast", 
    "libs/analyser", 
    "libs/ir", 
    "libs/interpreter", 
    "libs/compiler", 
    "catastrophici",
    "catastrophicc"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.65"
paw = "1.0.0"
structopt = { version = "0.3.26", features = ["paw"] }
dragon-tamer = { git = "https://github.com/samuelsleight/dragon-tamer" }

[workspace.dependencies.unic-emoji]
git = "https://github.com/eyeplum/rust-unic/"
branch = "develop"