[package]
name = "catastrophic-parser"
version = "0.0.0"
edition = "2018"
build = "build.rs"

[dependencies]
catastrophic-ast = { path = "../ast" }
lalrpop-util = "0.19.6"
regex = "1.5.4"
thiserror = "1.0.26"

[build-dependencies]
lalrpop = "0.19.6"
