name: Check Test Coverage

on: 
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

jobs: 
  check_coverage: 
    runs-on: ubuntu-latest
    container: 
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps: 
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install an appropriate version of llvm
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1.9.0
        with: 
          version: "14.0"

      # Check the code coverage
      - name: Check Coverage
        env: 
          LLVM_SYS_140_PREFIX: ${{ env.LLVM_PATH }}
        run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      # Submit to codecov.io
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with: 
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
